config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users, :controllers => { :registrations => "registrations" }, :path_prefix => 'd'
  devise_for :admins, :controllers => { :registrations => "registrations" } 
  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

  get 'welcome/faq'

  resources :questions

  resources :companies do
    resources :questions
  end

  root to: 'welcome#index'

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'

  resources :users, :only =>[:show]

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :company
	validates_presence_of :question
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index,:show]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @company = Company.find(params[:company_id])
    @question = @company.questions.create(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @company, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
        format.js 
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:company_id, :question, :author)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation" >
      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= message %>
        </div>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :company_id, class: 'control-label' %><br>
    <div class="controls">
    <%= f.number_field :company_id %>
  </div>
  </div>
  <div class="control-group">
    <%= f.label :question %><br>
     <div class="controls">
    <%= f.text_area :question %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :author %><br>
     <div class="controls">
    <%= f.text_area :author %>
    </div>
  </div>
  <div class="actions">
   <div class="controls">
    <%= f.submit 'Submit', class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/questions/_question.html.erb
<%= div_for question do %>
	
	<ul>
		<h2><%= h(question.question)%></h2><br>
		Posted by <%if(question.author!="")%><%= h(question.author) %>
		<%else%><%='Anonymity'%><%end%>
	</ul>
		<%end%>

app/views/questions/create.js.erb
var new_question = $("<%= escape_javascript(render(:partial => @question ))%>").hide();
$('#questions').prepend(new_question);
$('#question_<%= @question.id %>').fadeIn('slow');
$('#new_question')[0].reset();

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.company_id %></td>
        <td><%= question.question %></td>
        <td><%= question.author %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @question.company_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>