config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users, :controllers => { :registrations => "registrations" }, :path_prefix => 'd'
  devise_for :admins, :controllers => { :registrations => "registrations" } 
  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

  get 'welcome/faq'

  resources :questions

  resources :companies do
    resources :questions
  end

  root to: 'welcome#index'

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'

  resources :users, :only =>[:show]

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :questions, dependent: :destroy
	def self.search(query)
	  where("company like ?", "%#{query}%") 
	end
	validates_uniqueness_of :company
	validates_presence_of :company
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate, except: [:index, :show]
  before_action :authenticate_user!, :except => [:index,:show]

  # GET /companies
  # GET /companies.json
  def index
    if params[:search]
      @companies = Company.search(params[:search]).order("created_at DESC")
    else
      @companies = Company.all.order('created_at DESC')
    end
end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:index, :company)
    end

    def authenticate
      authenticate_or_request_with_http_basic do |name,password|
        name == "admin" && password == "ece"
      end
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div class="row">
<%= form_for @company, html: {class: 'form-horizontal'} do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= message%>
        </div>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :company, class: 'control-label' %><br>
    <div class="controls">
    <%= f.text_field :company %>
    </div>
  </div>
  <div class="control-group">
  <div class="controls">
    <%= f.submit 'Submit', class: 'btn btn-default' %>
    </div>
  </div>
<% end %>
</div>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<div class="row">
     <h1>Interview Reviews</h1>
     <%= link_to 'New Company', new_company_path, class: 'btn btn-mini btn-primary'%>
<div class="pull-right range-query">

<%= form_tag companies_path, method: :get do %>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag 'Search', :name => nil %>
<% end %>
</div>
</div>


<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Time Added</th>
          <th>Company</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @companies.sort_by{|m| m.company.downcase}.each do |company| %>
          
          <tr>
           <td><h3><%= company.created_at.strftime("%m/%d/%Y") %></h3></td>
            <td><h3><%= link_to company.company, company %></h3></td>
            <td><h3><%= link_to 'Edit', edit_company_path(company), class: 'btn btn-mini btn-success' %></h3></td>
            <td><h3><%= link_to 'Delete', company, method: :delete, class: 'btn btn-mini btn-danger',data: { confirm: 'Are you sure?' } %></h3></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>
</div>
<br>

<%= link_to 'New Company', new_company_path, class: 'btn btn-mini btn-primary'%>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  <%= @company.company %>
</h1>

<h3>Questions:</h3>

<div id='questions'>
	<%= render :partial => @company.questions.reverse %>
</div>

<%= form_for([@company, Question.new], remote: :true) do |f| %>
<p> <%= f.label :question, "New Interview Question", class: 'control-label' %><br />
	<%= f.text_area :question, :cols => "30", :rows => "10"%><br />
</p>
<p> <%= f.label :author, "author", class: 'control-label' %><br />
	<%= f.text_field :author%><br />
</p>
<p>
<%= f.submit "Add New Question",class: 'btn btn-info' %>
</p><%end%>
<br>
<br>
<p class="pull-middle"><%= link_to 'Edit', edit_company_path(@company),class: 'btn btn-mini btn-primary' %> |
<%= link_to 'Back', companies_path, class: 'btn btn-mini btn-primary' %>
</p>