config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users, :controllers => { :registrations => "registrations" }, :path_prefix => 'd'
  devise_for :admins, :controllers => { :registrations => "registrations" } 
  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

  get 'welcome/faq'

  resources :questions

  resources :companies do
    resources :questions
  end

  root to: 'welcome#index'

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'

  resources :users, :only =>[:show]

end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>Interviews</title>
  		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  		<%= csrf_meta_tags %>
	</head>

	<body>
		
		<div class="container">
			<%= render 'layouts/messages' %>
			<a href="http://www.ece.cmu.edu/">
				<img src="http://varma.ece.cmu.edu/GM-CMU-AD-CRL/logo-ece.jpg" height="142" width="342">
			</a>
			<ul class="nav nav-tabs">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Interviews", companies_path %></li>
				<li><%= link_to "About Us", welcome_about_path %></li>
				<li><%= link_to "Contact", welcome_contact_path %></li>
				<li><%= link_to "FAQs", welcome_faq_path %></li>
				
				<% if current_user %>
					<li class="pull-right"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li class="pull-right"><%= link_to "Sign Up", new_user_registration_path %></li>
					<li class="pull-right"><%= link_to "Sign In", new_user_session_path %></li>
				<% end %>

			</ul>

<!-- 			<% if flash[:notice] %>
				<div class="alert alert-success">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					<%= flash[:notice]%>
				</div>
			<% elsif flash[:error] %>
				<div class="alert alert-error">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					<%= flash[:error]%>
				</div>
			<% elsif flash[:alert] %>
				<div class="alert">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					<%= flash[:alert]%>
				</div>
			<%end%> -->
				
			<%= yield %>
		</div>
		<div>
			<br>
			<br>
			<br>
		</div>
	</body>
</html>